name: Deployment Metrics
on:
  push:
    branches:
      - master
jobs:
  ctoai-metrics:
    runs-on: ubuntu-latest
    steps:
      # { DEPLOYMENT STEP }
      - name: 'Report Deployment Succeeded'
        if: ${{ success() }}
        uses: cto-ai/action@v1.2
        id: ctoai-action
        with:
          team_id: ${{ secrets.TEAM_ID}}
          token: ${{ secrets.MEMORY_GAME_TOKEN }}
          event_name: "deployment"
          event_action: "succeeded"
          repo: 'memory-game'
      - name: 'Report Deployment Failed'
        if: ${{ failure() }}
        uses: cto-ai/action@v1.2
        id: ctoai-action
        with:
          team_id: ${{ secrets.TEAM_ID }}
          token: ${{ secrets.MEMORY_GAME_TOKEN }}
          event_name: "deployment"
          event_action: "failed"